- pkg/pillar/diskmetrics/usage.go
Signed-off-by: Naiming Shen <naiming@Administrators-MacBook-Pro.local>
>  SizeFromDir() can't find directory is ok, return size of zero then.

- pkg/pillar/zedcloud/authen.go
- pkg/pillar/zedcloud/send.go
Signed-off-by: eriknordmark <erik@zededa.com>
> pull the latest lfedge/eve

- pkg/kube/cluster-init.sh
- pkg/kube/multus-daemonset.yaml
- pkg/pillar/cmd/zedkube/appnetnotify.go
- pkg/pillar/cmd/zedkube/generatenispec.go
- add logging and rotation for multus
> added Multus logging and few minor changes

- pkg/pillar/kubeapi/vitoapiserver.go
- pkg/pillar/vault/handler_zfs.go
- some compiling issues after pulling the latest EVE
> fix compile issues after sync to latest EVE

- pkg/kube/cluster-init.sh
- pkg/kube/debuguser-role-binding.yaml
- pkg/pillar/cmd/volumemgr/updatestatus.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- pkg/pillar/cmd/zedkube/aitoapiserver.go
- pkg/pillar/types/zedmanagertypes.go
- add more clusterrole api-groups for debugging-user
- handle native container restart
> Support Native Container handling of device restart

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedrouter/appnetwork.go
- pkg/pillar/cmd/zedrouter/zedrouter.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/kubeapi/kubeapi.go
deleting vmi after reboot
temp commenting out zedrouter NI error of ACL after reboot
> Handle device restart for VM

- pkg/pillar/diskmetrics/diskmetrics.go
- pkg/pillar/kubeapi/vitoapiserver.go
If qcow2 actual-size is larger than virtual-size, use it for PVC size
> Handle thick qcow2

- pkg/alpine/mirrors/3.16/main
- pkg/kube/Dockerfile
> nfs-utils needed for longhorn rwx mounts

- pkg/kube/config.yaml
- pkg/pillar/vault/handler_zfs.go
- pkg/pillar/volumehandlers/zvolhandler.go
- pkg/pillar/zfs/zfs.go
Drop zvol block size to 4k, enable fast commits
> Minor etcd tuning

- pkg/pillar/cmd/volumemgr/volumemgr.go
- pkg/pillar/kubeapi/kubeapi.go
Check for daemonsets existing and for each to 
have a running and ready pod on the current node.
> volumemgr: wait for longhorn to be ready

- .gitignore
- Makefile
- pkg/external-boot-image/Dockerfile
- pkg/external-boot-image/build.yml
- pkg/grub/rootfs.cfg
- pkg/kube/Dockerfile
- pkg/kube/cluster-init.sh
- pkg/pillar/Dockerfile
- pkg/pillar/cas/containerd.go
- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/volumemgr/blob.go
- pkg/pillar/cmd/volumemgr/volumemgr.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/kubeapi/vitoapiserver.go
- pkg/pillar/scripts/create-image-to-qcow.sh
- pkg/pillar/volumehandlers/csihandler.go
- pkg/pillar/volumehandlers/handlers.go
- pkg/xen-tools/initrd/mount_disk.sh
This commit implements the Makefile changes to build and ship external-boot-image to support starting container as VM.
With this commit container as VM is fully functional.
> Compile ext boot image

- pkg/kube/kubevirt-operator.yaml
- updated kubevirt images to v1.1.0 of dec 11th code for eve's patch
> update kubevirt version v1.1.0 of dec 11th

- Makefile
- pkg/external-boot-image/Dockerfile
Fix compilation issues in pkg/kube after sync with master
> Fix Makefile to compile pkg/kube

- Makefile
- pkg/pillar/base/kubevirt.go
- pkg/pillar/cmd/zedkube/aitoapiserver.go
- pkg/pillar/cmd/zedkube/generatenispec.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/cmd/zedmanager/zedmanager.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/types/domainmgrtypes.go
- pkg/pillar/types/zedmanagertypes.go
- handle and convert eve name with underscore for sending to kubernetes
- Makefile temp change to allow Apple chip laptop crosscompiling kubervirt image
> Need to convert underscore in name, temp change for exteral-boot-imag Makefile

- pkg/pillar/vault/handler_zfs.go
- pkg/pillar/zfs/zfs.go
A small dev eden vm can ignore it.
> Allow ignoring reserve if on tiny system

- pkg/pillar/hypervisor/kubevirt.go
Delete extra code. external boot container is added under condition need9P
> Fix merge issue

- pkg/pillar/volumehandlers/csihandler.go
Create a block volume from qcow2.
> Create block volume

- pkg/kube/Dockerfile
- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/volumemgr/initialvolumestatus.go
- pkg/pillar/cmd/volumemgr/volumemgr.go
- pkg/pillar/cmd/zedkube/aitoapiserver.go
- pkg/pillar/cmd/zedkube/vnc.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/kubeapi/kubeapi.go
- pkg/pillar/kubeapi/nitoapiserver.go
- pkg/pillar/kubeapi/vitoapiserver.go
- pkg/pillar/types/kube.go
- pkg/pillar/types/locationconsts.go
- pkg/pillar/volumehandlers/csihandler.go
Refactored some code and upgraded virtual to v1.1.0
Tested that VM and Container gets deployed and works
> Refactor kubeapi and kubevirt.go

- pkg/kube/cluster-init.sh
- pkg/pillar/kubeapi/kubeapi.go
- change to use 'device-name' plus 5 bytes of uuid as suffix for node name of kubernetes
> kube node name to be device-name instead of uuid

- pkg/debug/scripts/collect-info.sh
Tested that zfs and Kubernetes info gets collected and also verified that /persist/newlog/kube/*.log are also collected.
Did not run ring10.suite since this script is not executed as part of that.
> Collect zfs and kube specific info

- pkg/pillar/hypervisor/kubevirt.go
> Strip the 0x prefix from the vendor and product id

- pkg/kube/eve-bridge/go.sum
- pkg/kube/eve-bridge/vendor/github.com/satori/go.uuid/.travis.yml
- pkg/kube/eve-bridge/vendor/github.com/satori/go.uuid/LICENSE
- pkg/kube/eve-bridge/vendor/github.com/satori/go.uuid/README.md
- pkg/kube/eve-bridge/vendor/github.com/satori/go.uuid/codec.go
- pkg/kube/eve-bridge/vendor/github.com/satori/go.uuid/generator.go
- pkg/kube/eve-bridge/vendor/github.com/satori/go.uuid/sql.go
- pkg/kube/eve-bridge/vendor/github.com/satori/go.uuid/uuid.go
- fix kube/eve-bridge vendor files
> fix vendor files in kube/eve-bridge

- pkg/pillar/kubeapi/vitoapiserver.go
- check service returned of api call before using it
- add more debug level to virtctl command for 'image-upload'
> add more debug level to virtctl image uploading

- pkg/kube/cluster-init.sh
The k3s.log file is gzip'd to a file name
of the pattern k3s.log.restart.<X>.gz where
X is the current RESTART_COUNT.
This enables easier debug of k3s crashes
as the crash reason will be at the bottom
of the compressed file. Also deleted some
redundant k3s start code which is already
run in check_start_k3s.
> Compress k3s logs before restarting.

- Makefile
- tools/makenet.sh
This is a copy of commit from master to get installer-net target to compile.
> Fix installer net, commit pulled from master

- pkg/kube/Dockerfile
- pkg/kube/config.yaml
- pkg/kube/iscsid.conf
Reduce queue depth to 1
Also enable local=path provider used by virtctl during image upload
> Add iscsid.conf 

- pkg/kube/cluster-init.sh
- pkg/kube/longhorn-config.yaml
Must usb-install to get 1.5.3 for now.
Branch includes previously merged k3s.yaml fix as well.  
Before copying, wait for k3s.yaml to exist.
> Move forward to longhorn 1.5.3

- pkg/edgeview/src/tcp.go
- fix an issue when using openssl encryption, the key sometime gets an invalid
> fix an issue of tcp/kube encryption of kubeconfig file

- pkg/pillar/cmd/volumemgr/handlecontent.go
- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/cmd/volumemgr/handlework.go
- pkg/pillar/cmd/volumemgr/updatestatus.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- pkg/pillar/cmd/zedmanager/handledomainmgr.go
- pkg/pillar/types/contenttreetypes.go
- pkg/pillar/types/locationconsts.go
- pkg/pillar/types/volumetypes.go
- remove the need for IsAppImg and OciImageName, etc to simplify the code
> Remove IsAppImg, OciImageName from the code

- pkg/pillar/cmd/volumemgr/handlevolume.go
> fix a check for iscontainer in pub volumestatus

- pkg/pillar/cmd/volumemgr/handlecontent.go
- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/cmd/volumemgr/handlevolumeref.go
- pkg/pillar/cmd/volumemgr/handlework.go
- pkg/pillar/cmd/volumemgr/updatestatus.go
- pkg/pillar/types/contenttreetypes.go
- pkg/pillar/types/locationconsts.go
Clean up code. Set docker.io prefix in content tree ReferenceID()
Delete all references of code where we are setting docker.io prefix
Set the Reference name in volrefstatus structure before publish.
Tested applifecyclemultiapps.suite and it passed.
> Cleanup the code for volume reference name publication

- pkg/pillar/cmd/volumemgr/handlecontent.go
- pkg/pillar/cmd/volumemgr/handlework.go
- pkg/pillar/cmd/volumemgr/updatestatus.go
- pkg/pillar/hypervisor/containerd_test.go
- pkg/pillar/types/contenttreetypes.go
More clean up. Tested applifecyclemultipapps.suite all good.
> Clean up more code from reviews

- pkg/pillar/cas/containerd.go
- pkg/pillar/cmd/volumemgr/blob.go
- pkg/pillar/cmd/volumemgr/volumemgr.go
Publish only Blobs that have eve-downloaded label
While creating images set label eve-downloaded=true on image and blobs
> GC support

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- pkg/pillar/cmd/zedkube/aitoapiserver.go
- pkg/pillar/cmd/zedmanager/handledomainmgr.go
- pkg/pillar/cmd/zedmanager/updatestatus.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/types/domainmgrtypes.go
Cleanup code in zed manager.
Verified that I can launch 
native container, container as VM and regular VM.
> Clean up zedmanager code

- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/kubeapi/nitoapiserver.go
- report to user if the cluster does not have ether NAD, for handling error
> add check for native container on ether passthrough NAD

- pkg/pillar/cipher/cipher.go
- pkg/pillar/cmd/zedkube/kubeinterface.go
- pkg/pillar/cmd/zedkube/zedkube.go
- add the missing code in zedkube cipher operation
> fix cipher decode issue of zedkube

- pkg/kube/cluster-init.sh
- pkg/kube/eve-bridge/eve-bridge.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- pkg/pillar/cmd/zedkube/kubeinterface.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/types/clustertypes.go
- make sure the node label apply is reliable
- non-bootsrap node waiting for cluster status before transit into cluster mode
- add a check in eve-bridge to skip cdi-upload- pod as Eve app
- comment out the cloud api for cluster config for now
- install route 10.43/16 towards the cluster prefix IP address, it seem to be needed if cluster interface w/o default route
>  - have bootstrap server w/ http query for cluster status

- pkg/pillar/cmd/zedkube/kubeinterface.go
- add a check to verify the config of cluster, exist if it's a single node case
- fix an typo.
> fix a crash at check kubesvc route, need to verify config is valid

- pkg/kube/cluster-init.sh
- added the saving /var/lib in singlenode mode, and copy them back in transition
> save /var/lib in singlenode, and convert back later

- pkg/kube/cluster-init.sh
Reduce memory usage due to logging
to overlayfs.
> Move pod logs to persist

- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/cmd/zedagent/handlevolume.go
- pkg/pillar/cmd/zedmanager/handledomainmgr.go
- pkg/pillar/cmd/zedmanager/updatestatus.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/types/volumetypes.go
- pkg/pillar/volumehandlers/csihandler.go
- pkg/pillar/volumehandlers/handlers.go
- have IsNoHyper flags in VolumeConfig and VolumeStatus, and treat them differently in terms of PVC handling
> handle nohyper containers differently since it does not need PVC

- pkg/pillar/cmd/zedkube/kubeinterface.go
fix an issue of only bootstrap node advertise cluster status which is not enough
> All nodes should advertise 'cluster' status if in cluster-mode

- pkg/kube/cluster-init.sh
Use full path to ctr (inside k3s) to avoid missing symlinks.
> Wait for containerd to start before importing external-boot-image

- pkg/kube/cluster-init.sh
Wait for all longhorn daemonsets to start, block saving snapshot of /var/lib until system is at a steady state.
> Don't report longhorn_initialized until ready

- pkg/pillar/base/kubevirt.go
- pkg/pillar/hypervisor/kubevirt.go
- to allow VMI migration during node isolation or down
- code to handle extra suffix for vmi name
> Implement VMI Replicaset for Applications

- pkg/kube/cluster-init.sh
- pkg/pillar/cmd/zedkube/cluster_pubsub.go
- pkg/pillar/cmd/zedkube/clusterstatus.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/hypervisor/kubevirt.go
- fix the issue of during cluster transition, node ip prefix may be empty
- VMI migration duration changed from default 5 minutes to 30 seconds
- fix the issue of cluster pubsub still sending configs even the configitem is false
>  Fix the issue of multus gets wrong node prefix

- pkg/kube/cluster-init.sh
- some of the descheduling, etc. can be submitted later for other PRs.
> Remove some of the lines from cluster-init.sh for later PRs

- pkg/pillar/cmd/zedkube/kubenodeop.go
- pkg/pillar/kubeapi/longhorninfo.go
A performance optimization if in delete node path. Fix for cluster delete path as all nodes cannot drain simultaneously.
> Don't drain in delete node path if no replicas on local node.

- pkg/pillar/docs/zedkube.md
- added documents to zedkube.md in pillar/docs
> Add components docs to zedkube module

- pkg/pillar/cmd/zedagent/zedagent.go
- pkg/pillar/cmd/zedkube/zedkube.go
And reduce some other verbose logging.
> Debug for empty error str to KubeClusterUpdateStatus

- pkg/pillar/cmd/baseosmgr/handlenodedrain.go
- pkg/pillar/cmd/diag/diag.go
- pkg/pillar/cmd/diag/handlenodedrain.go
- pkg/pillar/cmd/nodeagent/handlenodedrain.go
- pkg/pillar/cmd/zedagent/handlenodedrain.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/docs/zedkube.md
- pkg/pillar/kubeapi/kubetypes.go
- pkg/pillar/kubeapi/nodedrain.go
- pkg/pillar/kubeapi/nokube.go
Moving more code into microservice/handlenodedrain.go files.  Docs drain path cleanup.
> Drain path cleanup

- pkg/kube/config.yaml
Disable servicelb abd traffic which are not used in our kubevirt eve
> Disable servicelb and traefik

- pkg/pillar/cmd/zedkube/applogs.go
- pkg/pillar/cmd/zedkube/zedkube.go
- publish ENClusterAppStatus based on all node's status in cluster
- handle unreachable kube cluster on reset the ScheduledOnThisNode of AppStatus
> Handle ENC app-status and cluster reachable conditions

- pkg/pillar/kubeapi/storageutils.go
Only cleanup unmounted pvc and sdX DiskMetric.
This change has not completed initial test yet, submitted for early review.
> Don't unpublish IsDir DiskMetric objects

- pkg/pillar/cmd/zedkube/kubestatscollect.go
- pkg/pillar/cmd/zedkube/lease.go
- pkg/pillar/cmd/zedkube/zedkube.go
Channels might be cleaner here when time allows.
> Lease bool move to sync/atomics, many goroutines here.

- pkg/kube/config.yaml
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ 
https://docs.k3s.io/cli/server
> event-ttl under kube-apiserver-arg

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedkube/applogs.go
- fix a bug where getting the NodeInfo, not convert the underscore strings
> Need to convert underscore to dash character for node name

- pkg/kube/cluster-init.sh
- the token rotation in current code, only does once then wait forever, if in the case of applying this failed, we didn't have chance to retry. In this fix we'll retry every minute
- have a bug in waiting for bootstrap server status, we can fall into the 'else' condition, which may not be server already in 'cluster' status. we can get a wrong cert from server and can not recover
- printout log once a while if we can not https to bootstrap server while waiting
- if not all-pods-ready, not printing the misleading 'applying node labels' message, instead log the 'Not all pods are ready'
> Try to fix the token rotation failure and waitfor cluster status bug

- pkg/kube/cluster-init.sh
- when convert to single-node and to cluster mode in the same run, we need to wait for the bootstrap 'cluster' status before moving on
- there is an issue of k3s.log file rotation once a while, the k3s.log file can get to very large (like 30 Mbytes). Most likely the k3s server process is not releasing the file handler while the file size is truncated. Add a HUP signal before truncate the k3s.log file during rotation.
> Handle the case convert to single-node and immediately to cluster-mode

- pkg/pillar/diskmetrics/diskmetrics.go
- pkg/pillar/kubeapi/vitoapiserver.go
QCOW2 virt size, actual size, controller defined vol size.
> Restore checking image size, take max of all three

- pkg/pillar/agentbase/appinternalinfo.go
- pkg/pillar/cmd/zedkube/clusterstatus.go
- pkg/pillar/cmd/zedkube/zedkube.go
- added library function to call to print out all the related publish info on applicaiton
- handle app through tcp endpoint for cluster
> Cluster Application tracking through internal publications

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedagent/handlemetrics.go
- pkg/pillar/cmd/zedmanager/handleclusterapp.go
- pkg/pillar/cmd/zedmanager/updatestatus.go
- pkg/pillar/cmd/zedmanager/zedmanager.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/types/zedmanagertypes.go
I tested purge, failover and failback.
Looks ok.
@naiming-zededa its all your code anyway. Please review :) Only code I added is activateAIStatusUUID()
> Test purge

- pkg/pillar/agentbase/appinternalinfo.go
- pkg/pillar/cmd/zedkube/clusterstatus.go
- handle route without '/<app uuid or name>' for checking the clustering on each node
- add last 10 lines of k3s-install.log to the output
> Allow App-track to run on cluster info without app

- pkg/kube/cluster-update.sh
Wait for kubevirt and longhorn daemonsets to be ready first.
> Don't deschedule until node can support apps

- pkg/pillar/agentbase/apptracker.go
- pkg/pillar/cmd/zedkube/clusterstatus.go
- handle the neighbor cluster IP is unreachable, and implement timeout
- add 'CollectTime' to the app-tracker record
- change to file name to apptracker.go
- add AppNetworkConfig to the output
> Handle issues such as cluster-ip is unreachable
