- pkg/kube/src/eve-bridge/eve-bridge.go
- pkg/pillar/cmd/zedkube/appnetnotify.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/utils/volumeutils.go
- add check for pod running status after start it
- fix a golang format of previous merge
- change the 'eve-bridge' directory to /run/kube from /run/k3s
> Check for pod running status after start it

- pkg/edgeview/src/tcp.go
- pkg/kube/Dockerfile
- pkg/kube/cluster-init.sh
- pkg/kube/debuguser-role-binding.yaml
- create debugging-user for kubernetes cluster
- define roles for get,list only for kubernetes resources
- define roles for kubevirt for vm/vmi/console/vnc resource
- binding debugging-user to the cluster roles
- using edgeview to transport the user kubeconfig to user laptop
> Support RBAC for debugging-user kubernetes access w/ edgeview

- pkg/edgeview/src/basics.go
- pkg/edgeview/src/edge-view.go
- pkg/kube/debuguser-role-binding.yaml
- pkg/pillar/cmd/zedkube/aitoapiserver.go
- write user kubeConfig script to local path
- add role for eve-kube-app to allow 'kubectl exec -it' action for debugging-user
- fix an issue of container App logging with the correct pod name
> Kube edgeview decrypt script for kubeConfig

- pkg/kube/multus-daemonset.yaml
- pkg/newlog/cmd/newlogd.go
- in newlogd, have a filter to only allow 'warning'/'error' messages from container kube to upload
- forgot to remove private docker image of 'multus'
> filter kubernetes logs with only warning and error for uploading

- pkg/kube/Dockerfile
- pkg/pillar/cmd/zedmanager/handlezedrouter.go
- pkg/pillar/cmd/zedmanager/zedmanager.go
- pkg/pillar/cmd/zedrouter/pubsubhandlers.go
- from design doc review comment by Milan, it is better to decouple
the zedmanager from zedrouter's AppNetworkStatus message in
order to continue with the Domain creation work.
> decouple zedmanager from zedrouter for continue app domain creation

- pkg/pillar/cmd/zedmanager/handledomainmgr.go
- pkg/pillar/cmd/zedmanager/handlezedrouter.go
- pkg/pillar/cmd/zedmanager/updatestatus.go
- pkg/pillar/cmd/zedmanager/zedmanager.go
- pkg/pillar/cmd/zedrouter/pubsubhandlers.go
- make zedmanager to start without publish appnetworkconfig and without
existance of appnetworkstatus. sync appnetworkconfig creation in zedrouter with
appkubenetworkstatus publish by zedkube
- fix an issue of image is not ready in domainmgr when start an app
> Rework the zedmanager, zedrouter and zedkube interaction in app network

- pkg/pillar/cas/cas.go
- pkg/pillar/cas/containerd.go
- pkg/pillar/cmd/volumemgr/blob.go
- pkg/pillar/cmd/volumemgr/volumemgr.go
Since we use same containerd for eve downloads and Kubernetes downloads, we need to have a way to distinguish between eve downloaded images and k3s downloaded images.
This commit sets labels on images and blobs downloaded by eve (eve-downloaded=true) 
During GC we use  that flag to see if that image or blob  was downloaded by eve and then delete it.
> Handle GC of blobs and images

- pkg/pillar/cmd/zedmanager/handledomainmgr.go
Since kubevirt eve works with PVCs and PVC location and metadata is managed by Kubernetes, there is no activefilelocation on disk for those PVCs. So in case of kubevirt eve ignore file location check.
> Skip activefilelocation check for kubevirt

- pkg/kube/cluster-init.sh
Some longhorn versions are missing tar
which 'kubectl cp' uses
> Use cat/tee to write nsmounter

- pkg/grub/rootfs.cfg
- pkg/kube/cluster-init.sh
- pkg/pillar/Dockerfile
- pkg/pillar/cas/containerd.go
- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/volumemgr/blob.go
- pkg/pillar/cmd/volumemgr/volumemgr.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/kubeapi/vitoapiserver.go
- pkg/pillar/scripts/create-image-to-qcow.sh
- pkg/pillar/volumehandlers/csihandler.go
- pkg/pillar/volumehandlers/handlers.go
- pkg/xen-tools/initrd/mount_disk.sh
Handle launching container as VM
Disable GC for now until all issues are fixed.
For now external-boot-image container is downloaded from docker.io/zededapramodh/external-boot-scratch-container:2.0
If USB install is done that image is downloaded for you. 
Please run following command in eve Kube container manually.
ctr  -a /run/containerd-user/containerd.sock -n k8s.io  image pull docker.io/zededapramodh/external-boot-scratch-container:2.0
> Handle container launch as a VM

- pkg/kube/Dockerfile
- pkg/pillar/cmd/zedkube/aitoapiserver.go
- pkg/pillar/hypervisor/kubevirt.go
- it seems some type of VM not assigned with ip address in ztest due to 2nd intf
remove the cni0 default network interface when creating VMI
- fix a bug when multiple Apps using the same network-instance, it may get 
the wrong App for the network
- updated Kube alpine hash in dockerfile
> VMI remove cni0 interface, fix a bug in advertise appkubenetstatus

- pkg/kube/cluster-init.sh
- pkg/kube/kubevirt-operator.yaml
- pkg/pillar/cmd/zedmanager/handlezedrouter.go
- pkg/pillar/cmd/zedrouter/appnetwork.go
- need to chmod on /dev/null, which virt-handler checks
- a temp fix for zedmanager watchdog in some test case
> Fix and issue of Kubevirt v1.1.0 virt-handler pod crashing

- pkg/kube/cluster-init.sh
- pkg/kube/config.yaml
- pkg/kube/eve-bridge/eve-bridge.go
- pkg/kube/multus-daemonset.yaml
- move install.log, k3s.log, multus.log and eve-bridge.log into /persist/newlog/kube
> move kube logs to /persist/newlog/kube directory

- pkg/kube/config.yaml
Disable [netpol controller from kube-router](https://github.com/cloudnativelabs/kube-router/tree/v2.0/pkg/controllers/netpol).
> Disable network policies to avoid conflicts between EVE and kube-router

- pkg/kube/config.yaml
disable Traefik, cloud-controller and servicelb
That reduced 600MB of memory
> Disable traefik and cloud-controller

- pkg/kube/config.yaml
- pkg/kube/debuguser-role-binding.yaml
- pkg/pillar/base/kubevirt.go
- pkg/pillar/cmd/zedrouter/cni.go
- limit the app name to kubernetes w/ max of 32 characters (plus uuid prefix)
- reanable the k3s traefik and svclb, it seems to cause problems for PVCs if disabled
- allow storage class objects to be queried
> limit app name to kubernetes to max of 32 bytes, reanable traefik/svclb

- pkg/pillar/base/kubevirt.go
- either 32 bytes or len of the name string from pillar side
> need to check the name length for convert name

- pkg/kube/cluster-init.sh
Handle regression in switch to sqlite db where setting
the node-uuid label was lost.  Add handling for intermittent
small window of hostname returning linuxkit-*
> Set node-uuid label in k3s install path

- pkg/kube/nsmounter
The longhorn project has updated the nsmounter
script to search for a pid but still needs fixes
for finding our correct ns.  This commit does
two items: move up to the nsmounter longhorn
has in the 1.6 dev branch and add changes needed
to correctly find the pid in eve.
> Port forward to lh 1.6 nsmounter

- pkg/kube/debuguser-role-binding.yaml
- allow debug-users to do 'kubectl top [node | pod]' commands
> add clusterrole to allow metrics of node/pod

- pkg/kube/nsmounter
The containerd-shim name can lookup many k3s pod pids, this fixes that to consistently pick the correct pid.
> Change pid name to cluster-init.sh

- pkg/kube/cluster-init.sh
Don't copy it until it exists.
Closes small hole at boot time, apps would
wait forever at 'init' while pillar never sees k3s.yaml.
> Wait for k3s.yaml to exist.

- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/types/zfs.go
Add PCIReserve and PCIRelease to kubevirt hypervisor, same as kvm.go
Tested NVMe disk passthrough works fine.
> Add PCI reserve/release and also fix flooding of logs

- pkg/external-boot-image/Dockerfile
- pkg/xen-tools/initrd/chroot2.c
There is a regression in chroot2.c in base eve code. Due to that containers with non-root user id cannot start.
Fixed that. We need to check for getpwuid only after chroot is set.
After this fix grafana container starts
> Fix chroot to call getpwuid only after chroot is called

- pkg/debug/scripts/collect-info.sh
Otherwise the tar pulls in all containerd-user rootfs dirs
and tar generation takes an eternity.
> Skip root-run/containerd-user to avoid rootfs paths

- pkg/debug/scripts/collect-info.sh
- pkg/kube/Dockerfile
- pkg/kube/longhorn-generate-support-bundle.sh
Run longhorn-generate-support-bundle.sh to generate a longhorn supportbundle zip containing complete logs from longhorn pods and kubernetes env.
On each execution it will delete all bundles older than the most recent 5 to be respectful of disk space.
> collect-info.sh: Add longhorn supportbundle zip

- pkg/kube/config.yaml
local-path storage uses the /var/lib etcd fs be default which isn't large enough for the scratch pvcs cdi-upload creates.
This should be a short-term fix until completing a PR to reconfigure local-path's root dir and improve cdi upload speed.
> Re-disable local-path

- pkg/kube/debuguser-role-binding.yaml
- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedkube/aitoapiserver.go
- pkg/pillar/hypervisor/kubevirt.go
- remove some checks for io passthrough, check if it is native container
- skip io register to kubevirt if the ethernet name is not in ioadapter
- no need to generate NAD for io passthrough if it's a VM
> Changes for kubevirt VM ethernet passthrough

- pkg/pillar/vault/handler_zfs.go
- pkg/pillar/zfs/zfs.go
Also cleanup and organize constants.
Previous implementation left etcd-storage open, this PR causes new installs to encrypt etcd-storage identically to vault.
> Kubevirt etcd-storage zvol encrypted with vault

- pkg/pillar/cmd/zedagent/handlevolume.go
- pkg/pillar/cmd/zedmanager/handlevolumemgr.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/types/domainmgrtypes.go
- pkg/pillar/types/volumetypes.go
- pkg/pillar/volumehandlers/csihandler.go
These changes are for the review comments in https://github.com/lf-edge/eve/pull/3768
We do not need to set VolumeKey() and Key() for PVC. Just generate PVC name using  Volume UUID and generation counter.
Ran ztest suites ring0, applifecyclemultipapps.suite and they passed.
> Cleanup code in volumemgr

- pkg/kube/cluster-init.sh
multus-daemonset.yaml doesn't always apply successfully on the first try. Resolves a semi-rare install-time hang.
> Keep calling apply_multus_cni until yaml applies cleanly.

- pkg/pillar/hypervisor/kubevirt.go
rename should be unique for pciVendorSelector.  We cannot use the loop iterator, that is a bug.
If two apps are deployed on a device the rename will be same for both of them since the while loop will be executed for every app.
> Make resname unique per pcie address

- docs/BOOTING.md
- pkg/mkimage-raw-efi/install
- pkg/pillar/base/kubevirt.go
- pkg/pillar/vault/handler_zfs.go
- pkg/pillar/zfs/zfs.go
Addition of new grub boot option 'eve_install_kubevirt_etcd_sizeGB' which specifies the size of the etcd zvol on kubevirt images. Cleanup of RESERVE_EVE_STORAGE_SIZEGB which is not used until first boot. Move kubevirt specific eve_install option constants to kubevirt.go. Parse both eve_install_kubevirt_reserve_for_eve_sizeGB and eve_install_kubevirt_etcd_sizeGB in vault handler_zfs.go before creating the zvols.
A few yetus errors were fixed in the process.
> ZFS Vault Cleanup and eve_install_kubevirt_etcd_sizeGB boot option

- pkg/kube/cluster-init.sh
- pkg/pillar/cmd/nim/nim.go
- pkg/pillar/cmd/zedkube/kubeinterface.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/dpcreconciler/linux.go
- pkg/pillar/hypervisor/kubevirt.go
- fix an issue of node-uuid label using a wrong hostname string
- apply node-uuid label directly, not to check first
- move the SVC route from zedkube to nim and related reconcile functions
> Move kube SVC route from zedkube to nim/etc

- pkg/kube/cluster-init.sh
- a simple check and remove if dhcp daemon crashed and left .sock hang around.
> fix an issue during startup, dhcp can not be launched and hang

- pkg/kube/cluster-init.sh
Only import /etc/external-boot-image.tar if the image name in the tar file is docker.io/lfedge/eve-external-boot-image.  Additionally error checking around the re-tag step, only report success if it actually was.
> Tighter verification of external-boot-image

- pkg/debug/scripts/collect-info.sh
- pkg/pillar/cmd/zedkube/kubeinterface.go
- not to use kubeconfig cache in zedkube, cluster will change certificates
- put in the /persist/kubelog into collect-init.sh
> can not cache the kubeconfig in zedkube for cluster mode

- pkg/kube/cluster-init.sh
fix a bug which can missed the saved /var/lib when converting back to single node
> fix an issue directory check for save-var-lib

- pkg/kube/cluster-init.sh
- there can be a problem if we start containerd first then remove the /var/lib in restore.
> start containerd after the restoring of /var/lib

- pkg/kube/cluster-init.sh
- pkg/kube/config.yaml
- pkg/pillar/cmd/zedagent/zedagent.go
- pkg/pillar/cmd/zedkube/kubeinterface.go
- pkg/pillar/cmd/zedkube/zedkube.go
- kube k3s restart log taken only the last restart part instead of the current entire k3s.log file
- change the check_cluster_config_change to a separate task loop than the main cluster-init.sh loop, we can be stuck in certain condition and can not get out in order to check the cluster status change. This is to allow under any condition, we can get out of trouble and convert itself into a single-node, then convert back to cluster if needed
- when the bootstrap node is removed, the k3s/etcd keep generating large amount of logs, complainting about can not connect to proxy server, which is I think due to the 'agent tunneling' in k3s. Since we require all the nodes on the same network, we don't need this 'agent tunneling'. Thus set 'egress-selector-mode' to 'disabled' in k3s config file
- …
> Some additonal changes to kube container and k3s config

- pkg/kube/cluster-init.sh
- pkg/pillar/cmd/zedagent/zedagent.go
- pkg/pillar/cmd/zedkube/zedkube.go
- seen an issue when upgrade EVE image fails, the zedagent does not publish the ENC config using the previously check-pointed data. Causing the kube contain to decides moving to single-node mode even though it just connecting to the controller takes a while.
- skip the token change on non-bootstrap node, it does not seem to be necessary and can also causing issues
- in cluster-change background task, need to wait if the main task is in transition into cluster while waiting for the cluster status.
> Move back for EdgeNodeClusterConfig to /persist

- pkg/kube/cluster-init.sh
- pkg/pillar/cmd/zedkube/kubeinterface.go
- there could be a case zedkube publish the EdgeNodeCLusterStatus too late and kube accidentally switch into single-node mode
> Add a check during startup to prevent switch to single node accidentally

- pkg/pillar/kubeapi/kubeapi.go
The default replica of virt-controller and virt-operator were two, resulting in a total of 6 pods. As the replica is modified to default to one, changing pods count to four.
> Changed waitForNodeReady to look for No. of pod items < 4

- pkg/pillar/base/kubevirt.go
- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/volumemgr/handlecontent.go
- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/cmd/volumemgr/handlevolumeref.go
- pkg/pillar/cmd/zedagent/clusterpubsub.go
- pkg/pillar/cmd/zedagent/handlecontent.go
- pkg/pillar/cmd/zedagent/handlevolume.go
- pkg/pillar/cmd/zedkube/applogs.go
- pkg/pillar/cmd/zedkube/cluster_pubsub.go
- pkg/pillar/cmd/zedkube/kubenodeop.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/cmd/zedmanager/handledomainmgr.go
- pkg/pillar/cmd/zedmanager/zedmanager.go
- pkg/pillar/cmd/zedrouter/cni.go
- pkg/pillar/cmd/zedrouter/ipam.go
- pkg/pillar/dpcreconciler/linux.go
- pkg/pillar/hypervisor/containerd.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/hypervisor/kvm.go
- pkg/pillar/hypervisor/null.go
- pkg/pillar/hypervisor/xen.go
- pkg/pillar/types/contenttreetypes.go
- pkg/pillar/types/domainmgrtypes.go
- convert native container pod into replicatset
- use EdgeNodeInfo for getting the node name and uuid for domainmgr
- domainmgr prevent delete app due to app not showing up, it's a replicaset, domainmgr should not worry about deleting
- try to fillin the volumemgr Volume Reference name for container, which needs to be kept all the way through volumemgr -> zedmanager -> domainmgr
- some temp code on cluster pubsub
- generate uniform random Mac address across cluster nodes for App
> Add mechanism for application/container migration in cluster

- pkg/kube/Dockerfile
- pkg/kube/cluster-init.sh
- pkg/kube/cluster-update.sh
- pkg/kube/descheduler-job.yaml
- pkg/kube/descheduler-policy-configmap.yaml
- pkg/pillar/cmd/baseosmgr/handlenodedrain.go
- pkg/pillar/cmd/zedagent/handlenodedrain.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- pkg/pillar/cmd/zedagent/zedagent.go
- pkg/pillar/cmd/zedkube/handlenodedrain.go
- pkg/pillar/cmd/zedkube/kubenodeop.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/docs/zedkube.md
- pkg/pillar/kubeapi/kubetypes.go
- pkg/pillar/kubeapi/nodedrain.go
Descheduler follows user defined policy to select pods and evict them to reach certain goals such as node utilization, re-scheduling, node failure
and add operations.
Fixes:
- reorganize zedkube startup to handle nodeuuid/nodename set inside pubsub handler EdgeNodeInfo to always overwrite whatever os.Hostname gave us before.
- Fix cordon detection
- Add new option to detect a consistent/persistent kube api outage and allow bypass of drain.  Next commit will make this opt-in via a config-property instead.
- Allow followon baseos updates to re-request drain after a previous drain failure.
- Move uncordon to a goroutine which waits for EdgeNodeInfo and then progressively checks for api access,
node ready, then checks cordon state.
> kubevirt: add descheduler for rebalancing

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedkube/applogs.go
- pkg/pillar/cmd/zedkube/zedkube.go
Also check for hasprefix for the contVMIname also.
With this fix both VMs and Pods are showing correct status in the UI.
> Set nodename to lowercase when querying for pods

- pkg/kube/cluster-init.sh
- pkg/kube/cluster-update.sh
Also fix a pattern found in a few spots where there was both an unnecessary 'grep' and 'wc -l'.
Instead move the node name into the get node/<name> and move the 'wc -l' into the grep with '-c'
> Delay Descheduler until local node is Ready

- pkg/pillar/base/kubevirt.go
- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedkube/applogs.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/hypervisor/kubevirt.go
- to allow VMI migration during node isolation or down
- code to handle extra suffix for vmi name
- Set nodename to lowercase when querying for pods Also check for hasprefix for the contVMIname also
> Implement VMI Replicaset for Applications

- pkg/kube/cluster-init.sh
- the /run/eve-release string is used partially to be display in kubernetes, this is useful in particular with clustering with multiple nodes
```
☁  ~  k get node -o wide
NAME          STATUS   ROLES                       AGE     VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                   KERNEL-VERSION                  CONTAINER-RUNTIME
plex1-7050m   Ready    control-plane,etcd,master   4d23h   v1.28.5+k3s1   10.244.244.1   <none>        poc-oct03-2024-02db99a6                    6.1.106-linuxkit-06a737b0f212   containerd://1.7.11-k3s2
plex2-7050m   Ready    control-plane,etcd,master   28h     v1.28.5+k3s1   10.244.244.2   <none>        Unknown                                    6.1.106-linuxkit-06a737b0f212   containerd://1.7.11-k3s2
plex3-7050m   Ready …
```
> Allow kubectl get node to have OS-IMAGE feild display EVE release

- pkg/pillar/cmd/baseosmgr/handlenodedrain.go
- pkg/pillar/cmd/volumemgr/handlediskmetrics.go
- pkg/pillar/cmd/volumemgr/handlepvcdiskmetrics.go
- pkg/pillar/cmd/volumemgr/nokube.go
- pkg/pillar/cmd/zfsmanager/zfsstoragemetrics.go
- pkg/pillar/kubeapi/nokube.go
- pkg/pillar/kubeapi/storageutils.go
Lookup sd block device major:minor
Used to lookup pv dev and then pvc name.
Fill three maps with the device relationships
at the beginning of the DiskMetric creation
loop to keep this lightweight.
For each createOrUpdatePvcDiskMetrics():
- one kubernetes api pvc list
- one syscall.stat per /dev/sdX device
- one syscall.stat per /dev/longhorn/<pv> device
Skip attempting to match volumestatus to zvol
on kubevirt images.
Fix: avoid error log on single node kubevirt
image when updating baseosmgr
Signed-off-by: Andrew Durbin <andrewd@zededa.com>
(cherry picked from commit fe281b675eda96b83e1ad83f56eca4037d9ca365)
> Create volumemgr/DiskMetric for kubevirt PVCs

- pkg/newlog/cmd/newlogd.go
- if the memlogd sends source of 'kube' logs, drop them without uploading to the controller side.
> Remove kube container logs to be uploading to controller

- pkg/pillar/cmd/zedkube/clusterstatus.go
- when converting to from cluster mode. there can be a chance the NIM sents network-status changes, which could cause zedkube to publish an empty EdgeNodeClusterStatus, that will break the converting to single-node mode.
> Fix an issue of publishing empty EdgeNodeClusterStatus

- pkg/kube/cluster-init.sh
- if the default route interface has two ip prefixes, the node-ip should only take one of them as the ip for kubernetes
> Fix an issue in single node provisoning, nodeip may get two IPs

- pkg/debug/scripts/collect-info.sh
> Include /persist/kubelog in collect-info tar

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/hypervisor/containerd.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/hypervisor/kvm.go
- pkg/pillar/hypervisor/null.go
- pkg/pillar/hypervisor/xen.go
- pkg/pillar/types/domainmgrtypes.go
- remove the nodename string param added to Setup() function, use the DomainStatus 'NodeName' variable to pass in. This way we don't change a number of kvm.go, null.go, containerd.go, etc files.
> Change Task Setup function not to introduce new param

- pkg/pillar/hypervisor/kubevirt.go
This enables the descheduler to evict them as pods
> Apply descheduler annotation to VMIs

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/types/domainmgrtypes.go
- a new flag in DomainStatus, DomainConfigDeleted and that will be set only in the case of DomainConfig is removed. We'll not do domain delete from domainmgr to the kubernetes unless this flag is set. In kubernetes, the config is stored in database, there is no need to delete it due to status check failed
> Handle application delete operation in domainmgr

- pkg/debug/scripts/collect-info.sh
- pkg/kube/config.yaml
Default is 1hr which drops useful debug info.
> Extend event ttl to 24hr, dump in collect-info

- pkg/kube/cluster-update.sh
Don't publish kube update status until applied-kube-version above 0.
> Don't report baseos_updating until after components installed.

- pkg/pillar/cmd/zedagent/handlemetrics.go
Find the domainmgr/DomainStatus where .DomainName matches the AppInstanceStatus.DomainName. If this is found, set the .ClusterAppRunning flag to match DomainStatus.Activated.
> Set ClusterAppRunning to show the node failover destination of an app.

- pkg/pillar/cmd/volumemgr/handlevolume.go
> Don't log.Fatal here for replicated volumes

- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/cmd/zedagent/handlemetrics.go
- pkg/pillar/cmd/zedkube/applogs.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/cmd/zedmanager/handleclusterapp.go
- pkg/pillar/cmd/zedmanager/updatestatus.go
- pkg/pillar/cmd/zedmanager/zedmanager.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/kubeapi/vitoapiserver.go
- pkg/pillar/types/clustertypes.go
This is rework of PR https://github.com/naiming-zededa/eve/pull/390/
Retested everything.
With this commit only node that is running the app will publish the AppInstanceStatus.
If the app gets scheduled on a node AppInstanceStatus will be created and published.
If the app gets de-scheduled , unpublishAppInstanceStatus will be called.
zedkube will now publish first  ENCAppStatus only when app gets scheduled on the node and its a designated node id.
> Handle failover and volmgr changes

- pkg/pillar/cmd/zedkube/applogs.go
- in multiple applications case, the there is a bug since now we changed the logic to not always publish the ENClusterAppStatus, need to use the correct oldStatus for the application
> Fix an issue in checkAppsStatus() of using staled oldStatus{}

- pkg/kube/config.yaml
- pkg/pillar/cmd/volumemgr/handlediskmetrics.go
- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/cmd/zedkube/applogs.go
1) Add !foundpod to publish ENCAppstatus on designated node
2) If its a replicated PVC the maxvolsize in config and status may not match, so ignore it
3) FileLocation may not be set for PVC, since PVC is not present in /persist location, ignore that for kubevirt eve and publish app disk metrics.
> Fix some bugs found in testing

- pkg/pillar/cmd/zedmanager/handleclusterapp.go
Remove  updateAIStatusUUID from handleENClusterAppStatusImpl(). We don't need that. If there is update required there is a normal eve code path which does that. 
So basically handleENClusterAppStatusImpl() is very simple.
If app scheduled on me {
if no aiStatus {
create and publish
}
} else {
// app not on me.
if aiStatus {
unpublishAppInstanceStatus()
}
}
I tested multiple failovers, all seems to be good.
> We do not need to updateAIStatusUUID from handleENClusterAppStatusImpl

- pkg/pillar/hypervisor/kubevirt.go
kubevirt_vmi_memory_domain_bytes_total doesn't exist. Add comments with link to docs for easier lookup later.
> Switch kubevirt metric for AllocatedMB field.

- pkg/pillar/cmd/volumemgr/handlediskmetrics.go
- pkg/pillar/types/diskmetrics.go
Ignore /persist/kubelog and /persist/kube-save-var-lib when generating disk metrics
> Ignore kube specific directories in /persist for DiskMetrics

- pkg/pillar/kubeapi/vitoapiserver.go
Sometimes upload retries succeed with an error but the output string "already successfully imported/cloned/updated".
> Fix upload status workaround to use output

- pkg/pillar/cmd/baseosmgr/handlebaseos.go
Found in manual testing when one node failed loading baseos blobs but began drain anyways.
> Wait until blob loading complete: LOADED

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- pkg/pillar/hypervisor/kubevirt.go
- pkg/pillar/types/domainmgrtypes.go
- removed the check for DNid for app deletion, we'll do for all
- remove the delete() and cleanup(), stop() not for kubevirt code, since we now return 'Unknown' which needs to be handled outside kubevirt
- if we don't get status for a pod/vmi, we will return 'unknown' status, but we register the starting timestamp, if longer than 5 mins, we treat this as 'Halt' status.
- remove the max wait for nodeinfo publication at the beginning of domainmgr function, we always wait, it should be there
- sime misc fixes.
> Handle code review in main branch PR 4407

- pkg/pillar/dpcreconciler/linux.go
- pkg/pillar/iptables/connmark.go
- the current ACL in mangle table miss the allowing for kube related inbound packets in edge-node clustering. When the NI with flowlog is enabled, it blocks those packets and breaks the clustering
> Handle kubernetes inbound packets with flowlog enabled

- pkg/pillar/cmd/domainmgr/domainmgr.go
- pkg/pillar/cmd/zedagent/parseconfig.go
- since the code moved to get the EdgeNodeInfo to the beginning of domainmgr startup, before onboarding, even though the EdgeNodeInfo subscribe gets triggered, but it may not have any content.
- also the check fatal is only valid for kubevirt mode.
- move the parseEdgeNodeInfo from App section to device section.
> Fix a crash at domainmgr not getting EdgeNodeInfo

- pkg/pillar/cmd/zedkube/lease.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/types/zedkubetypes.go
- when encounter errors, the previous code exit which would disable the lease election for the node. put in retry timer to retry later
- change the duration of lease to 15/60/300 seconds
- add publication of KubeLeaseInfo, otherwise it is not visable for any debugging if there is problem
- add logging when the election RunOrDid() function if it exit
- change the start/stop channel from blocking to 1 buffer, the previous code could miss the start/stop actions due to the goroutine busy and being dropped
> Fix a number of kube lease election issues

- pkg/pillar/cmd/volumemgr/handlediskmetrics.go
- pkg/pillar/cmd/volumemgr/handlepvcdiskmetrics.go
- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/cmd/volumemgr/handlevolumeref.go
- pkg/pillar/cmd/volumemgr/updatestatus.go
- pkg/pillar/kubeapi/longhorninfo.go
- pkg/pillar/kubeapi/vitoapiserver.go
- pkg/pillar/volumehandlers/csihandler.go
Allocated space is only available from lh volume object status.
PVC should be created with app inst vol defined size not img.
Set FileLocation in Populate() so its published automatically.
Fix missing VolumeStatus after modifying in volumemgr/AppDiskMetrics.
Shorter timeout set in k8s api calls for metrics path.
> Metrics Cleanup: Fix pvc allocated space reporting and pvc size at creation time.

- pkg/pillar/cmd/zedkube/lease.go
- pkg/pillar/cmd/zedkube/zedkube.go
- pkg/pillar/types/clustertypes.go
- pkg/pillar/types/zedkubetypes.go
- changed the renew deadline from 1 min to 3 mins
- added a boolean 'ElectionRunning' for lease status publication
- when lease election exit due to timed out, we need to retry to start the lease routine again
> Fix an issue when lease renew timedout due to api-server unreachable

- pkg/kube/cluster-init.sh
etcd has been reverted, these are all unreferenced now.
> Remove replica images when converting to single node.

- pkg/xen-tools/Dockerfile
Included to fix the build from HTTP 400 seen on the old path.
Original commit message:
The liburing-0.7 is missing from the original source URL. This change updates the source URL to kernel.org.
Signed-off-by: Shahriyar Jalayeri <shahriyar@zededa.com>
(cherry picked from commit 2ba0fe1749d2dcdc365e57cb30198bf14725a362)
> update liburing source URL to kernel.org

- pkg/pillar/cmd/volumemgr/handlevolume.go
- pkg/pillar/volumehandlers/csihandler.go
When we reboot the node and restart the container app, we need to set the content format to container to launch it as shim VM.  Though we convert the container image to PVC, we still need to set the format as container.
This is day one bug, which is caught now !
I tested multiple restarts and container vmi starts fine and I was able to access it through VNC
> Set the content format as container for container apps

- pkg/pillar/diskmetrics/usage.go
syscall.Stat.Blocks are always reported as 512 size. (libc struct stat st_blocks).  
Use thin allocation check when dir has prefix of
types.VolumeEncryptedDirName or types.VolumeClearDirName
to handle subdirs.
> Fix persist-vault-volumes UsedBytes for lh snapshots
